01_create_and_install_gem_master_locally:
  script:
    - cd master 
    - gem build opstat-master.gemspec
    - "mkdir -p /home/builds/admin/opstat-master"
    - "cp opstat-master-`ruby -e 'require \"./lib/opstat-master/version.rb\"; puts Opstat.version'`.gem /home/builds/admin/opstat-master"
    - "gem install /home/builds/admin/opstat-master/opstat-master-`ruby -e 'require \"./lib/opstat-master/version.rb\"; puts Opstat.version'`.gem"

rspec:
  script:
  - rspec spec

