name: Create Tag on Merge to Master

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version from version.rb
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=VERSION = ")[^"]*' version.rb)  # Adjust the path to your version.rb file
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create Tag
        run: |
          git tag "v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"

      - name: Output the tag name
        run: echo "Created tag: v${{ env.VERSION }}"
