name: Create Tag on Merge to Master, build and push gems to RubyGems

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version from version.rb
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=VERSION = ")[^"]*' version.rb)  # Adjust the path to your version.rb file
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create Tag
        run: |
          git tag "v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"

      - name: Output the tag name
        run: echo "Created tag for version v${{ env.VERSION }}"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          gem install bundler

      - name: Build and push gems
        env:
          RUBYGEMS_AUTH_TOKEN: ${{ secrets.RUBYGEMS_AUTH_TOKEN }} # Set this secret in your GitHub repository
        run: |
          for dir in plugins master client; do
            cd $dir
            gem build *.gemspec
            gem push *.gem
            cd ..
          done
